name: Continuous Integration

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

permissions: read-all

jobs:
  tfsec:
    name: Terraform Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute security check
        uses: aquasecurity/tfsec-action@v1.0.0
  checkov:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute Checkov
        run: |
          docker run --tty --rm --volume ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --config-file .checkov.yaml
