name: Continuous Integration

on:
  push:
    branches: "**"
    # branches: [ main ]
  pull_request:
    branches: "**"

permissions: read-all

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  tflint:
    name: Lint Terraform Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.44.1
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run TFLint
        run: tflint -f compact ./infrastructure
  tfsec:
    name: Terraform Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute security check
        uses: aquasecurity/tfsec-action@v1.0.0
  checkov:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute Checkov
        run: |
          docker run --tty --rm --volume ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --config-file .checkov.yaml
  datree:
    runs-on: ubuntu-latest
    name: Datree K8s Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute Datree policy check
        uses: datreeio/action-datree@main
        with:
          path: "**/*.yaml"
          cliArguments: "--only-k8s-files"
